version: 2.1
jobs:
  build:
    docker:
      - image: circleci/erlang:20.3.8.22
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run EUnit
          command: make eunit
